---
name: My-First-Run
env:
  APP_NAME: "AppName-version:$GITHUB_RUN_NUMBER"
  name_file: app.txt
on: 
   push:
     branches: 
        - main

  
jobs:
  my_testing_lint:
    
    runs-on: ubuntu-latest

    
    steps:
      - name: Print Hello World
        run: echo " Hello world"
      - name: Print Hostname
        run: hostname
      - name: List Folder
        run: ls -la
      - uses: actions/setup-python@v4.8.0
        with:
           python-version: 3.8
      - name: Upgrade PIP
        run: python -m pip install --upgrade pip
      - name: GIT CLONE
        uses: actions/checkout@v4
        
                  
      - name: List Folder
        run: ls -la

       
  my_testing_unit:
    
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Print Hello World to Deploy
        run: | 
         echo " Hello world Deploy"
         echo " Name APP ${{env.APP_NAME}}"
      - name: Print Hostname
        run: hostname
      - name: Create a file
        run: echo "I won't live long" > ${{ env.name_file }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.name_file }}-name
          path: ${{ env.name_file }}
          retention-days: 5

  my_deploying:
    
    runs-on: ubuntu-latest
    needs: [my_testing_lint,my_testing_unit]
    
    steps:
      
      - name: What version programm
        run: |
          echo "Docker version"
          echo "----------------"
          docker --version
          echo " ------------"
          echo " AWS Version"
          aws --version
          echo " --------------"

      - name: Docker build
        uses: docker/build-push-action@v5.1.0
        with:
           file: docker/Dockerfile
           tags: appname:latest
      - name: Print Login
        with:
           username: ${{secrets.Github_User}}
        run: |
           echo " ${{secrets.Github_User}}"
