---
name: My-First-Run
env:
  APP_NAME: "AppName.version.$GITHUB_JOB
  
on: 
   push:
     branches: 
        - main

  
jobs:
  my_testing:
    
    runs-on: ubuntu-latest

    
    steps:
      - name: Print Hello World
        run: echo " Hello world"
      - name: Print Hostname
        run: hostname

  my_deploying:
    
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
      - name: Print Hello World to Deploy
        run: | 
         echo " Hello world Deploy"
         echo " Name APP ${{env.APP_NAME}}"
      - name: Print Hostname
        run: hostname
      
